// AUTO-GENERATED by engine/mine_chemistry_claims.js — do not edit by hand.
//
// CHEMISTRY_CLAIMS: pair-level chemistry phrases mined from the editorial
// pair-note corpus. Indexed by [drinkFlavor][foodFlavor] -> { clause, count }.
// Generator consults at composition time when a (drink-flavor x food-flavor)
// match exists for a pair under construction.
// ---------------------------------------------------------------------------
const CHEMISTRY_CLAIMS = {
  "acid": {
    "base": { "clause": "the bright acid cuts the cream base", "count": 4 },
    "bisque": { "clause": "the bright acid cuts the bisque", "count": 8 },
    "char": { "clause": "the bright acid cuts the char", "count": 3 },
    "cream": { "clause": "the acid cuts the burrata cream", "count": 4 },
    "saut": { "clause": "the acid cuts the saut", "count": 12 },
    "soup": { "clause": "the bright acid cuts the soup", "count": 16 }
  },
  "acidity": {
    "fish": { "clause": "the crisp acidity frames the fish cleanly", "count": 26 },
    "plate": { "clause": "the crisp acidity sits with the plate", "count": 33 },
    "side": { "clause": "the crisp acidity sits with the light side", "count": 6 },
    "weight": { "clause": "the bright acidity frames the fish without weight", "count": 44 }
  },
  "agave": {
    "craft": { "clause": "the clean additive-free agave lifts the burrata with premium craft", "count": 4 }
  },
  "agave-pepper": {
    "char": { "clause": "the agave-pepper carries the char", "count": 16 }
  },
  "anise": {
    "char": { "clause": "the anise frames the char", "count": 3 },
    "cream": { "clause": "the anise underlines the cream", "count": 5 },
    "edge": { "clause": "the anise threads the herb edge", "count": 12 }
  },
  "apple-pear": {
    "base": { "clause": "the apple-pear lifts the broccoli base", "count": 5 }
  },
  "bitter": {
    "fat": { "clause": "the bitter cuts the fat", "count": 9 }
  },
  "body": {
    "bird": { "clause": "the concentrated body carries the herb-crisped bird", "count": 19 },
    "cap-fat": { "clause": "the opulent body meets the cap-fat", "count": 5 },
    "cut": { "clause": "the velvety body lifts the lean cut", "count": 8 },
    "fish": { "clause": "the crisp body frames the fish cleanly", "count": 55 },
    "plate": { "clauses": [
      "the crisp body sits with the plate",
      "the crisp body matches the plate",
      "the crisp body carries the plate",
      "the crisp body wraps the plate",
      "the crisp body rests against the plate"
    ], "count": 102 },
    "side": { "clause": "the crisp body sits with the light side", "count": 27 },
    "strip": { "clause": "the concentrated body carries the strip", "count": 8 }
  },
  "caramel": {
    "butter": { "clause": "the caramel rounds the herb butter", "count": 53 },
    "char": { "clause": "the caramel echoes the grilled char", "count": 29 },
    "character": { "clause": "the caramel meets the nut character", "count": 11 },
    "earthy": { "clause": "the caramel rounds the earthy plate", "count": 28 },
    "umami": { "clauses": [
      "the caramel rounds the umami plate",
      "the caramel softens the umami weight",
      "the caramel underlines the umami plate",
      "the caramel threads the umami register",
      "the caramel balances the umami plate"
    ], "count": 98 }
  },
  "cassis": {
    "butter": { "clause": "the cassis frames the herb butter", "count": 7 },
    "char": { "clause": "the cassis plays against the grilled char", "count": 39 },
    "edge": { "clause": "the cassis underlines the green edge", "count": 8 }
  },
  "cedar": {
    "char": { "clause": "the cedar plays against the char", "count": 3 },
    "depth": { "clause": "the cedar plays against the earth depth", "count": 5 },
    "richness": { "clause": "the cedar plays against the lactic richness", "count": 3 }
  },
  "character": {
    "depth": { "clause": "the aged-but-clear character meets the sear with more depth", "count": 3 },
    "digestif": { "clause": "the sweet character meets the savory plate at digestif", "count": 8 },
    "distinctiveness": { "clause": "the agave-forward camarena character lifts the burrata with craft distinctiveness", "count": 11 },
    "fat": { "clause": "the bourbon character meets the rendered fat", "count": 12 },
    "register": { "clauses": [
      "the bourbon character meets the dessert at digestif register",
      "the bourbon depth folds into the dessert at digestif weight",
      "the bourbon body sits with the dessert at digestif register",
      "the bourbon register rests against the dessert close",
      "the bourbon weight settles into the dessert close"
    ], "count": 127 },
    "sugar": { "clause": "the sweet character mirrors the dessert sugar", "count": 37 }
  },
  "cherry-fruit": {
    "char": { "clause": "the cherry-fruit cuts the char", "count": 21 },
    "cream": { "clause": "the cherry-fruit rounds the cream", "count": 28 },
    "depth": { "clause": "the cherry-fruit frames the umami depth", "count": 30 },
    "edge": { "clause": "the cherry-fruit lifts the herb edge", "count": 13 }
  },
  "chocolate": {
    "base": { "clause": "the dark chocolate plays against the spinach base", "count": 3 },
    "depth": { "clause": "the chocolate frames the bone depth", "count": 3 },
    "richness": { "clause": "the dark chocolate plays against the lactic richness", "count": 3 }
  },
  "citrus": {
    "char": { "clause": "the citrus cuts the rich char", "count": 9 },
    "herbs": { "clause": "the citrus lifts the herbs", "count": 10 }
  },
  "cocoa": {
    "char": { "clause": "the cocoa underlines the grilled char", "count": 20 },
    "chocolate": { "clause": "the cocoa underlines the chocolate", "count": 4 }
  },
  "coffee": {
    "caramel": { "clause": "the coffee meets the caramel", "count": 8 },
    "cream": { "clause": "the coffee threads the cream", "count": 35 }
  },
  "depth": {
    "bird": { "clause": "the bourbon depth carries the herb-crisped bird", "count": 15 },
    "cap-fat": { "clause": "the barrel-aged depth meets the cap-fat", "count": 13 },
    "cut": { "clause": "the bourbon depth carries the cut", "count": 26 },
    "dessert": { "clause": "the aged-oak depth threads the dessert", "count": 80 },
    "fat": { "clause": "the bourbon depth cuts the umami fat", "count": 59 },
    "plate": { "clause": "the barrel-aged depth carries the plate", "count": 21 },
    "savory": { "clause": "the caramel-oak depth threads the savory plate", "count": 52 },
    "side": { "clause": "the whiskey depth meets the indulgent side", "count": 31 },
    "soup": { "clause": "the aged depth sits with the soup", "count": 3 },
    "starter": { "clause": "the aged-oak depth meets the rich starter", "count": 49 }
  },
  "dried-fruit": {
    "spice": { "clause": "the dried-fruit echoes the spice", "count": 4 }
  },
  "earth": {
    "base": { "clause": "the clayey earth plays against the spinach base", "count": 3 },
    "char": { "clause": "the forest-floor earth plays against the vegetal char", "count": 3 }
  },
  "edge": {
    "cream": { "clause": "the mineral edge cuts the cream", "count": 29 },
    "fat": { "clause": "the bitter herb edge cuts the umami fat", "count": 3 },
    "fish": { "clause": "the mineral edge lifts the fish", "count": 53 },
    "green": { "clause": "the mineral edge frames the green plate", "count": 4 },
    "meat": { "clause": "the mineral edge mirrors the briny meat", "count": 52 },
    "richness": { "clause": "the mineral edge cuts the rich plate", "count": 4 },
    "shellfish": { "clause": "the floral edge frames the shellfish", "count": 4 },
    "side": { "clause": "the botanical edge sits with the light side", "count": 77 },
    "soup": { "clause": "the bitter herb edge frames the light soup", "count": 20 }
  },
  "espresso": {
    "char": { "clause": "the espresso plays against the char", "count": 3 }
  },
  "finish": {
    "soup": { "clause": "the high-acid finish cuts the soup", "count": 3 }
  },
  "fruit": {
    "char": { "clause": "the fresh fruit plays against the vegetal char", "count": 3 }
  },
  "graphite": {
    "depth": { "clause": "the graphite plays against the smoky mineral depth", "count": 3 },
    "umami": { "clause": "the graphite plays against the truffle-oil umami", "count": 3 }
  },
  "honey": {
    "char": { "clause": "the honey rounds the grilled char", "count": 25 },
    "cream": { "clause": "the honey threads the cream", "count": 61 }
  },
  "juniper": {
    "shellfish": { "clause": "the juniper carries the shellfish", "count": 15 }
  },
  "leather": {
    "depth": { "clause": "the leather plays against the smoky mineral depth", "count": 3 }
  },
  "lift": {
    "fish": { "clauses": [
      "the botanical lift frames the fish cleanly",
      "the botanical lift carries the fish cleanly",
      "the botanical lift brightens the fish",
      "the bright lift threads the fish",
      "the botanical lift underlines the fish"
    ], "count": 176 },
    "side": { "clause": "the cocktail lift sits with the light side", "count": 20 },
    "soup": { "clause": "the cocktail lift sits with the light soup", "count": 43 },
    "weight": { "clause": "the cocktail lift carries the shellfish without weight", "count": 4 }
  },
  "mocha": {
    "base": { "clause": "the mocha plays against the spinach base", "count": 3 },
    "char": { "clause": "the mocha plays against the beefy char", "count": 4 },
    "crust": { "clause": "the mocha plays against the golden crust", "count": 5 },
    "richness": { "clause": "the mocha plays against the lactic richness", "count": 3 },
    "sauce": { "clause": "the mocha plays against the earthy sauce", "count": 3 }
  },
  "mousse-and-acid": {
    "plate": { "clause": "the mousse-and-acid sits with the plate", "count": 22 }
  },
  "mousse-and-citrus": {
    "bird": { "clause": "the mousse-and-citrus lifts the herb-crisped bird", "count": 3 }
  },
  "neutrality": {
    "plate": { "clause": "the vodka neutrality sits with the plate", "count": 60 }
  },
  "oak": {
    "char": { "clause": "the oak underlines the char", "count": 48 },
    "cream": { "clauses": [
      "the oak rounds the cream",
      "the oak threads the cream",
      "the oak frames the rich cream",
      "the oak depth lays under the cream",
      "the oak softens the cream"
    ], "count": 107 },
    "sugar": { "clauses": [
      "the oak frames the caramelized sugar",
      "the oak underlines the burnt sugar",
      "the oak threads the caramelized sugar",
      "the oak balances the burnt-sugar edge",
      "the oak softens the caramelized sugar"
    ], "count": 100 },
    "umami": { "clauses": [
      "the oak frames the umami",
      "the oak threads the umami plate",
      "the oak underlines the umami weight",
      "the oak depth meets the umami",
      "the oak balances the umami register"
    ], "count": 158 }
  },
  "orange": {
    "cream": { "clause": "the orange lifts the cream", "count": 5 },
    "spice": { "clause": "the orange meets the spice", "count": 4 }
  },
  "peel": {
    "chocolate": { "clause": "the orange peel echoes the chocolate", "count": 5 }
  },
  "plum": {
    "depth": { "clause": "the plum plays against the earth depth", "count": 3 }
  },
  "profile": {
    "butter": { "clause": "the clean profile carries the herb butter", "count": 25 },
    "fish": { "clause": "the neutral profile frames the fish cleanly", "count": 46 },
    "register": { "clause": "the jamaican dark-rum molasses profile frames the cream at workhorse register", "count": 3 },
    "side": { "clause": "the neutral profile sits with the light side", "count": 29 }
  },
  "red": {
    "cut": { "clause": "the medium-body red frames the lean cut", "count": 18 },
    "green": { "clause": "the medium-body red frames the green plate", "count": 30 },
    "register": { "clause": "the medium-body red meets the cap-fat at lighter register", "count": 24 },
    "savory": { "clause": "the medium-body red meets the savory plate", "count": 30 },
    "side": { "clause": "the medium-body red sits with the rich side", "count": 22 },
    "soup": { "clauses": [
      "the medium-body red meets the light soup",
      "the medium-body red sits with the light soup",
      "the medium-body red threads the light soup",
      "the medium-body red brightens the light soup",
      "the medium-body red rests against the light soup"
    ], "count": 99 }
  },
  "silk": {
    "soup": { "clause": "the low-tannin silk lifts the soup", "count": 5 }
  },
  "smoke": {
    "broth": { "clause": "the smoke threads the broth", "count": 3 },
    "butter": { "clause": "the smoke frames the herb butter", "count": 12 },
    "char": { "clause": "the smoke meets the char", "count": 60 },
    "cut": { "clause": "the smoke frames the lean cut", "count": 6 },
    "depth": { "clause": "the smoke meets the umami depth", "count": 48 },
    "fat": { "clause": "the smoke cuts the umami fat", "count": 4 },
    "plate": { "clause": "the smoke meets the plate", "count": 10 },
    "richness": { "clause": "the smoke meets the cheese richness", "count": 7 },
    "shellfish": { "clause": "the smoke wraps the briny shellfish", "count": 9 },
    "side": { "clause": "the smoke layers into the rich side", "count": 4 }
  },
  "spice": {
    "butter": { "clause": "the spice meets the herb butter", "count": 6 },
    "char": { "clause": "the baking spice plays against the grilled char", "count": 4 },
    "depth": { "clause": "the spice frames the umami depth", "count": 29 },
    "dessert": { "clause": "the spice threads the dessert", "count": 55 },
    "green": { "clause": "the spice lifts the green plate", "count": 27 },
    "richness": { "clause": "the rye spice cuts the rich plate", "count": 10 }
  },
  "structure": {
    "cut": { "clause": "the cab structure carries the bone-in cut", "count": 3 },
    "depth": { "clause": "the cab structure meets the savory depth", "count": 32 },
    "tenderloin": { "clause": "the cab structure frames the tenderloin", "count": 8 }
  },
  "sweetness": {
    "butter": { "clause": "the rounded sweetness meets the herb butter", "count": 13 },
    "cream": { "clause": "the rounded sweetness threads the cream", "count": 5 },
    "crust": { "clause": "the caramelized sweetness mirrors the crust", "count": 3 },
    "dessert": { "clause": "the dessert-wine sweetness threads the dessert", "count": 6 },
    "edge": { "clause": "the rounded sweetness softens the green edge", "count": 69 }
  },
  "tannin": {
    "fish": { "clause": "the silken tannin frames the fish", "count": 17 },
    "starter": { "clause": "the firm tannin cuts the rich starter", "count": 22 }
  },
  "vanilla": {
    "char": { "clauses": [
      "the vanilla softens the grilled char",
      "the vanilla rounds the flame-grilled char",
      "the vanilla balances the char-and-fat",
      "the vanilla brightens the grilled char-edge",
      "the vanilla underlines the rendered char"
    ], "count": 123 },
    "cream": { "clauses": [
      "the vanilla rounds the cream",
      "the vanilla folds into the cream",
      "the vanilla brightens the cream",
      "the vanilla underlines the rich cream",
      "the vanilla lifts the cream"
    ], "count": 247 }
  },
  "violet": {
    "depth": { "clause": "the violet plays against the earth depth", "count": 4 }
  },
  "weight": {
    "char": { "clause": "the aged-oak weight carries the flame-grilled char", "count": 14 },
    "cut": { "clause": "the aged-oak weight frames the lean cut", "count": 22 }
  }
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CHEMISTRY_CLAIMS };
} else if (typeof window !== "undefined") {
  window.CHEMISTRY_CLAIMS = CHEMISTRY_CLAIMS;
}
