// AUTO-GENERATED by engine/mine_tier_corrections_and_competitors.js
// COMPETITOR_REFS: per (foodClass, drinkClass) the bottle that v9 says
// "still cuts it harder" or "still leads". Used in verdict generation.
const COMPETITOR_REFS = {
  "HEARTY_STARTER": {
    "BOURBON_BOLD": { bottle: "Fernet Branca", count: 24 },
  },
};
module.exports = { COMPETITOR_REFS };
